version: '3.8'
services:
  talan:
    build:
      context: .
      target: development
    ports:
      - "8087:8080"
    environment:
      - SERVER_PORT=8080
      - POSTGRES_URL=jdbc:postgresql://postgres/talan
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=talan
      - POSTGRES_USER=talan
      - POSTGRES_DB=talan

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres